### ISSUE TITLE
another error while make

### ISSUE THREAD

**Issue by prateek-khandelwal** [nongio-zz/rik.theme#2]
Hi Riccardo, 

This is a strange issue.
I have successfully build your theme and tried it out too.
However, strangely, the build is failing now, 

error being - 
`Rik+Button.m:11:60: error: ‘OBJC_ASSOCIATION_COPY’ undeclared (first use in this function)
objc_setAssociatedObject(self, kRikIsDefaultButton, val, OBJC_ASSOCIATION_COPY);`

If I understand it correctly, the object_setAssociationObject is handled by objC runtime. 
I am not able to figure this out completely

Can you suggest something ?

Complete gist for make-
https://gist.github.com/prateek-khandelwal/f525e0ca6dd06d0df2c4

**Comment by nongio-zz** [comment]
Hi, try to import:
`
#import <objc/runtime.h>
`
in Rik+Button.m
take a look here: http://nshipster.com/associated-objects/

**Comment by prateek-khandelwal** [comment]
oh yes, I did try that earlier too, still the same errors. 
I think it is my Obj C runtime that is the root of the problem, which I am not able to fix.

**Comment by prateek-khandelwal** [comment]
Yes, the issue is local to my system, successfully compiled the theme on a fresh vbox (using clang runtime though) 
sorry to bother you.
